<?php
// $Id$
/**
 * @file - shows a library patron's data.
 *
 */
/**
 * Implementation of hook_block
 */
define('DEFAULT_API','http://wwwdev.library.cornell.edu/cgi-bin/ilsapi2.cgi?netid=');
function patroninfo_block($op='list', $delta=0, $edit=array()) {
        global $user;
        switch ($op) {
                case 'list':
                        $blocks[0]['info'] = t('PatronInfo');
		        $blocks[0]['cache'] = BLOCK_NO_CACHE;
                        return $blocks;
                case 'view':
			views_include("tabs");
			views_add_css('admin');
                        _patroninfo_add_local(); 
                        $ts  = new views_tabset; 
			$netid = cu_authenticate();
		        if (isset($netid) && $netid != '') { 	
                        $blocks['subject'] = t('PatronInfo');
                        $url=variable_get('patroninfo_target', DEFAULT_API).$netid;
		        // someone might set the api address to null.
		        if (strlen($url)<7) { $url = DEFAULT_API.$netid; } 
			$stuff = file_get_contents($url);
                        // the json decode gets all twisted up if the json is not utf-8, and if it contains tabs.
		        // at the moment some of the data is utf-8, and some iso-8859-1. got to fix this.
                        $str = iconv("ISO-8859-1", "UTF-8", $stuff);
			$str =  strtr( $str,"\t", " ");
		        $var = json_decode($str); 
			$cindex = 0;
                        foreach($var->items as $item) {
                            $note = '';
			    if (($item->status == 'chrged') || 
                             ($item->status == ' RECEIVED') 
                             ) { 
			      if ($item->od == $item->rd) { $due = $item->od;} else { $due=$item->rd;}
                              if (strlen($item->re) > 0) { $note = "Recalled. Please note due date."; $due = $item->re;}
                              if (!empty($item->vstatus)) { $note .= ' ' .$item->vstatus;}
                              $cdatad[]= array($due,$item->tl . t('Location:').$item->lo." $note",'');
                              $scdatad[] = array(index => $cindex++,  due => $due); 
                              $cdata.= '<li class=patroninfo-item>'.$item ->tl. ' '. $due .  t(' borrowed from '). $item ->lo. '</li>';
		            }
			    if ( ($item->status == 'Unfilled') || 
                             ($item->status == 'Cancelled')) { 
			      if ($item->od == $item->rd) { $due = $item->od;} else { $due=$item->rd;}
                              if (strlen($item->re) > 0) { $note = "Recalled. Please note due date."; $due = $item->re;}
                              if (!empty($item->vstatus)) { $note .= ' ' .$item->vstatus;}
                              $ndatad[]= array($due,$item->tl . t('Location:').$item->lo." $note",'');
                              $ncdatad[] = array(index => $nindex++,  due => $due); 
                              $ndata.= '<li class=patroninfo-item>'.$item ->tl. ' '. $due .  t(' borrowed from '). $item ->lo. '</li>';
		            }
			    if ($item->status == ' SHIPPED' || $item->status == 'pahr') { 
			      $shipped = $item->ed; 
                              $odatad[]= array($shipped,$item->tl,$item->lo);
                              $odata.= '<li class=patroninfo-item>'.$item->tl.t('is on its way to you for pickup at : ').
                              $item ->lo. '</li>';
		            }
			    if ($item->status == 'waiting') { 
                              if (isset($item->url) && $item->url != '') { 
                                $at = _link(t('Get It!'),'patroninfo-link', $item->url);
                              } else {
                                $at = $item->lo;
                              }
			      $before = $item->ed; 
                              $wdatad[]= array($before,$item->tl,$at);
                              $wdata.= '<li class=patroninfo-item>'.$item ->tl.t('is waiting for you : '). $item ->lo. '</li>';
		            }
			    if ($item->status == 'finef') { 
			      $am = substr($item->am,0,strlen-2).'.'.substr($item->am,-2); 
                              $fdatad[]= array($item->ed,$item->tl,$am);
                              $fdata.= '<li class=patroninfo-item>'.$item ->tl.t('was due:'). $item ->od.t(' at '). $item ->lo. 
                                                t('Amount:') .$item->am .'</li>';
		            }
                          }  
                          if($cindex) { // only sort if there is something there. 
                              foreach ($scdatad as $key => $row) { $dates[$key]  = $row['due']; }
                             // Sort the data with dates ascending
                             // Add $scdatad as the last parameter, to sort by the common key
                             array_multisort($dates, SORT_ASC, $scdatad);
                             foreach ($scdatad as $key => $row) {
                               $cdatadx[$row['index']]  = $cdatad[$row['index']];
                             }
                             $cdatad = $cdatadx;
                           }
			  $you = $var->patron->last.','.$var->patron->given;
                          $blocks['content'] = "<h2>".t('Patron info for')." $you</h2>";
			  $p1=array($cdatad,array(t('Due on'),t('Description'),t('Renew(not functional)')),t('Checked out'));
			  $p2 = array($wdatad,array(t('Pickup before'),t('Description'), t('At')),t('Available'));
			  $p3 = array($odatad,array(t('Pickup before'),t('Description'), t('At')),t('In Process'));
			  $p4 = array($fdatad,array(t('Incurred on'),t('Description'), t('Amt')),t('Fines and fees'));
			  $p5 = array($ndatad,array(t('Date'),t('Item and Message'), t('At')),t('Notices'));
		          $blocks['content'] .=   _patroninfo_tabs(array($p1,$p2,$p3,$p4,$p5));
                          if (variable_get('patroninfo_debug',0)) {
                               $blocks['content'] .= "URL:$url<br/>$stuff<br/>"; 
                          }
                          return $blocks;
			} else { // we should never reach this point.  if we do, reality is no longer in existence. 
			$dest = 'http://dss-es287linux.library.cornell.edu/apache2-default/test/netid.php';
			setcookie ("callback", "/apache2-default/webvision/xaboutme");
			drupal_goto($dest);
			}
        }
}

/**
 * Implementation of hook_menu().
 */
function patroninfo_menu() {
  $items = array ();
  $items['admin/settings/patroninfo'] = array (
      'title' => t('ILS api client'),
      'description' => t('Configure settings for ils api.'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('patroninfo_admin_settings'),
      'access arguments' => array('configure ils api feeds'),
      'type' => MENU_NORMAL_ITEM);
 return $items;
} 

function patroninfo_admin_settings() {
  $form['patroninfo_template'] = array(
    '#type' => 'textfield',
    '#title' => t('Patron Info template'),
    '#default_value' => variable_get('patroninfo_target', 'http://libdev.library.cornell.edu/~es287/classes/ilsapi.cgi?netid='),
    '#description' => t('URL of the target cgi that returns ils info. The user netid is added at the end. netid is the parm.'),
    '#maxlength' => 256,
  );
  $form['patroninfo_debug'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show debug info'),
    '#default_value' => variable_get('patroninfo_debug', 0),
    '#description' => t('Show debug info'),
  );
  $form['#submit'] = array('patroninfo_admin_settings_submit');

  return system_settings_form($form);
}

function patroninfo_perm() {
  return array('configure ils api feeds');
}

/**
 * Validation function;
 *
 */
function patroninfo_admin_settings_validate(&$form, $form_state) {
}

/**
 * Submits the admin settings form and saves all the variables.
 */
function patroninfo_admin_settings_submit($form, &$form_state) {
  variable_set('patroninfo_target', $form_state['values']['patroninfo_template']);
  variable_set('patroninfo_debug', $form_state['values']['patroninfo_debug']);
}

/**
 * returns a formatted link 
 */
function _link($label,$class, $link) {
 $uclass = ' class="'.(isset($class) ? $class : 'link') . '" '; 
 return "<a$uclass href='$link'>$label</a>" ;
}

/**
 * returns a formatted link 
 */
function _format_table($legend,$datad, $col_one,$col_two,$col_three,$clapsed = TRUE) {
   $fstitle = $legend.' (' .sizeof($datad).')';
   $bc = theme_table(array($col_one, $col_two, 
                     $col_three),$datad, null,$legend);
   $fieldset = array('#title' => $fstitle, '#collapsible' => TRUE,'#collapsed' => $clapsed, '#value' => $bc);
   //$fieldset = array('#title' => $fstitle, '#collapsible' => FALSE,'#collapsed' => $clapsed, '#value' => $bc);
   return  theme('fieldset', $fieldset) ;
}
/**
 * returns tabs formatted like primary tabs. 
 * ptabs is an array of arrays -- each element is an array of data, and an array of labels.
 * first is array of data, second is array of items, third is just label. eg 
 *    array($wdatad,array(t('Pickup before'),t('Description'), t('At')),t('Available'));
 */
function _patroninfo_tabs($ptabs) {
  $ul = '<div id="pi-tabs" class="xtabs"><ul>' . "\n";
  $tabn = 0;
  foreach($ptabs as $item) {
    $bc = theme_table($item[1],$item[0], null,$item[2]);
    $ul .= "<li><a href=\"#frag-$tabn\"><span>".$item[2] . '(' . sizeof($item[0]) .')</span></a></li>' . "\n"; 
    $dv .= "<div id=\"frag-$tabn\">".$bc.'</div>' . "\n"; 
    $tabn++;
  }
  $ul .= '</ul>';
  $output .= $ul.$dv . '</div>' . "\n";
  return $output;
}

/**
 * add js, both standard files, and inline boilerplate for patroninfo module.
 */
function _patroninfo_add_local() {
   drupal_add_js(drupal_get_path('module', 'patroninfo') .'/js/patroninfo-ui.core.js');
   drupal_add_js(drupal_get_path('module', 'patroninfo') .'/js/patroninfo-ui.tabs.js');
   //drupal_add_js(drupal_get_path('module', 'patroninfo') .'/js/patroninfo-divheader.js');
   drupal_add_css(drupal_get_path('module', 'patroninfo') .'/css/patroninfo-flora.pi.css');
   $boiler = '$(document).ready(function(){ $("#pi-tabs > ul").tabs(); });';
   drupal_add_js($boiler,'inline');
}
